baseURL = "http://www.renayoung.com/"
title = "Serena Young"
languageCode = "en-us"
ignoreFiles = ["\\static-src$"]

[params]

    [params.social]
        linkedin = "https://www.linkedin.com/in/renaf/"
        github = "https://github.com/renaf479"

[taxonomies]
range = "range"
slug = "slug"