baseURL = "http://www.serenayoung.com/"
title = "Serena Young | Portfolio"
languageCode = "en-us"
ignoreFiles = ["\\static-src$", "\\main.sass.css$", "\\main.sass.css.map$"]

[params]

    [params.meta]
        title = "Serena Young"
        type = "website"
        url = "http://serenayoung.com"
        description = "Frontend Web Developer. And I also make things"
        ie = "This site was optimized for modern browsers. Please try Chrome, Safari, Firefox, or IE Edge for a better experience."

    [params.landing]
        title = "Serena Young"

    [params.about]
        title = "About Me"
        image = "/assets/images/about/about.jpg"

    [params.works]
        title = "Works"
        content = "A selection of the works I've helped create"

    [params.contact]
        title = "Say Hi!"
        url = "https://goo.gl/forms/LnOcdaBegdyMlH2B3"

    [params.social.linkedin]
        title = "Linkedin"
        url = "https://www.linkedin.com/in/renaf/"
        slug = "linkedin"

    [params.social.github]
        title = "Github"
        url = "https://github.com/renaf479"
        slug = "github"

    [params.social.resume]
        title = "Resume"
        url = "/assets/files/SerenaYoung_CV.pdf"
        slug = "resume"

[taxonomies]
year = "years"
slug = "slugs"
position = "positions"
imageLeft = "imagesLeft"
primaryColor = "primaryColor"