baseURL = "http://www.renayoung.com/"
title = "Site"
languageCode = "en-us"
ignoreFiles = ["\\static-src$"]

[params]

    [params.landing]
        name = "Serena Young"
        title = "Web Developer"

    [params.works]
        title = "Works"
        content = "A selection of the works I've helped create"

    [params.social.linkedin]
        title = "Linkedin"
        url = "https://www.linkedin.com/in/renaf/"
        slug = "linkedin"

    [params.social.github]
        title = "Github"
        url = "https://github.com/renaf479"
        slug = "github"

    [params.social.resume]
        title = "Resume"
        url = "https://github.com/renaf479"
        slug = "resume"

[taxonomies]
year = "years"
slug = "slugs"
position = "positions"
imageLeft = "imagesLeft"
imageRight = "imagesRight"
primaryColor = "primaryColor"