baseURL = "http://www.renayoung.com/"
title = "Serena Young | Portfolio"
languageCode = "en-us"
ignoreFiles = ["\\static-src$"]

[params]

    [params.landing]
        title = "Serena Young"

    [params.works]
        title = "Works"
        content = "A selection of the works I've helped create"

    [params.contact]
        title = "Say Hi!"
        url = "https://goo.gl/forms/LnOcdaBegdyMlH2B3"

    [params.social.linkedin]
        title = "Linkedin"
        url = "https://www.linkedin.com/in/renaf/"
        slug = "linkedin"

    [params.social.github]
        title = "Github"
        url = "https://github.com/renaf479"
        slug = "github"

    [params.social.resume]
        title = "Resume"
        url = "https://github.com/renaf479"
        slug = "resume"

[taxonomies]
year = "years"
slug = "slugs"
position = "positions"
imageLeft = "imagesLeft"
primaryColor = "primaryColor"