baseURL = "http://www.renayoung.com/"
title = "Site"
languageCode = "en-us"
ignoreFiles = ["\\static-src$"]

[params]

    [params.social.linkedin]
        title = "Linkedin"
        url = "https://www.linkedin.com/in/renaf/"
        slug = "linkedin"

    [params.social.github]
        title = "Github"
        url = "https://github.com/renaf479"
        slug = "github"

[taxonomies]
range = "range"
slug = "slug"